# Generated by Django 4.2.5 on 2023-10-11 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_totais', models.IntegerField()),
                ('Ano_Letivo', models.CharField(max_length=9)),
                ('id_Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='G_Estagios.empresa')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='G_Estagios.curso')),
            ],
        ),
    ]
