# Generated by Django 4.2.5 on 2023-10-11 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0002_curso_empresa_estagio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='id_Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_Estagios.empresa'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_Estagios.curso'),
        ),
        migrations.CreateModel(
            name='Assiduidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_created=True)),
                ('id_Aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
