# Generated by Django 4.2.5 on 2023-10-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0005_polo_customuser_is_coordenador_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
