# Generated by Django 4.2.5 on 2023-10-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0006_customuser_confirmation_code_customuser_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_code',
        ),
    ]
