# Generated by Django 4.2.6 on 2023-10-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0007_remove_customuser_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_confirmed',
        ),
    ]
