# Generated by Django 3.2.6 on 2023-11-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0008_remove_customuser_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
