# Generated by Django 3.2.6 on 2023-12-15 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0010_customuser_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Texto', models.TextField(blank=True)),
                ('curso', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Docs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('data', models.DateField(auto_created=True, blank=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(blank=True, upload_to='Documentos/Assiduidade/')),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_Estagios.tipo_docs')),
                ('id_Aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
