# Generated by Django 3.2.6 on 2023-12-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0011_alertas_documentos_tipo_docs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentos',
        ),
        migrations.DeleteModel(
            name='Tipo_Docs',
        ),
    ]
