# Generated by Django 3.2.6 on 2023-12-19 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0012_auto_20231215_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolos',
            name='id_Aluno',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ano',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('protocolo', 'Protocolo'), ('cv', 'Currículo'), ('assiduidade', 'Assiduidade'), ('relatorio', 'Relatório')], max_length=20)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='estagio',
            name='Assiduidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assiduidade', to='G_Estagios.documento'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='id_Protocolos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='protocolos', to='G_Estagios.documento'),
        ),
        migrations.DeleteModel(
            name='Assiduidade',
        ),
        migrations.DeleteModel(
            name='Protocolos',
        ),
    ]
