# Generated by Django 3.2.6 on 2023-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0013_auto_20231219_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='mes',
            field=models.CharField(blank=True, choices=[('fev', 'Fevereiro'), ('mar', 'Março'), ('abr', 'Abril'), ('mai', 'Maio'), ('jun', 'Junho'), ('jul', 'Julho'), ('ago', 'Agosto')], max_length=3),
        ),
    ]
