# Generated by Django 3.2.6 on 2023-12-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0015_remove_customuser_is_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ano',
        ),
    ]
