# Generated by Django 3.2.6 on 2023-12-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0017_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='localizacao',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
