# Generated by Django 3.2.6 on 2023-12-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0018_empresa_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='Ano_Letivo',
            field=models.CharField(blank=True, help_text='Formato: YYYY/YYYY', max_length=9, null=True),
        ),
    ]
