# Generated by Django 3.2.6 on 2023-12-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0020_remove_estagio_assiduidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagio',
            name='id_Protocolos',
        ),
        migrations.AddField(
            model_name='estagio',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='estagios', to='G_Estagios.Documento'),
        ),
    ]
