# Generated by Django 3.2.6 on 2023-12-21 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0022_alter_estagio_id_tutor_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='estagio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Documentos', to='G_Estagios.estagio'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='Estagio', to='G_Estagios.Documento'),
        ),
    ]
