# Generated by Django 3.2.6 on 2023-12-21 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0023_auto_20231221_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
