# Generated by Django 3.2.6 on 2024-01-05 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0024_alertas_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
