# Generated by Django 3.2.6 on 2024-01-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0025_auto_20240105_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='escola',
        ),
    ]
