# Generated by Django 3.2.6 on 2024-01-05 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_Estagios', '0026_auto_20240105_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='G_Estagios.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='escola',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='G_Estagios.polo'),
            preserve_default=False,
        ),
    ]
